AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Stack

Parameters:
  NetworkStackName:
    Type: String

Resources:
  # Lambda
  JakartaJSLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile:
          Fn::Join:
          - "\n"
          - - "'use strict';"
            - exports.handler = (event, context, callback) => {
            - '  const data = { event, context };'
            - '  console.log(JSON.stringify(data, null, 4));'
            - "  callback(null, data);"
            - "};"
      Description: AWS Loft Demo Lambda
      FunctionName: jakartajs-demo-lambda
      Handler: index.handler
      Role: !GetAtt JakartaJSLambdaExecutionRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue:
              !Sub ${NetworkStackName}-JakartaJSSecurityGroup
        SubnetIds:
          - Fn::ImportValue:
              !Sub ${NetworkStackName}-JakartaJSSubnet1
          - Fn::ImportValue:
              !Sub ${NetworkStackName}-JakartaJSSubnet2
          - Fn::ImportValue:
              !Sub ${NetworkStackName}-JakartaJSSubnet3
      Tags:
        - Key: Stack
          Value: jakartajs-demo
      Runtime: nodejs10.x
      MemorySize: 512
      Timeout: 15
      DeadLetterConfig:
        TargetArn: !GetAtt JakartaJSDLQ.Arn

  # Execution Role
  JakartaJSLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: jakartajs-demo-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: jakartajs-demo-lambda-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - '*'
            Resource: '*'
      Path: '/'
      Tags:
        - Key: Stack
          Value: jakartajs-demo

  # SQS
  JakartaJSDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: jakartajs-Demo-DLQ
      VisibilityTimeout: 10
      MessageRetentionPeriod: 1209600
      Tags:
        - Key: Stack
          Value: jakartajs-demo

Outputs:
  # Lambda
  JakartaJSLambda:
    Value: !Ref JakartaJSLambda
    Export:
      Name: !Sub ${AWS::StackName}-JakartaJSLambda

  # Execution Role
  JakartaJSLambdaExecutionRole:
    Value: !Ref JakartaJSLambdaExecutionRole
    Export:
      Name: !Sub ${AWS::StackName}-JakartaJSLambdaExecutionRole

  # SQS
  JakartaJSDLQ:
    Value: !Ref JakartaJSDLQ
    Export:
      Name: !Sub ${AWS::StackName}-JakartaJSDLQ
